# See https://pre-commit.com/ for usage and config
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: no-commit-to-branch
    name: Check not master branch
    args: ['--branch', 'master']
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: detect-aws-credentials
    args: ['--allow-missing-credentials']
  - id: detect-private-key
  - id: end-of-file-fixer
    exclude: 'docs/|setup.cfg'
  - id: trailing-whitespace
    exclude: 'docs/|setup.cfg'

- repo: https://github.com/timothycrosley/isort
  rev: 5.7.0
  hooks:
    - id: isort

- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black
    exclude: ^migrations/

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.0
  hooks:
  - id: flake8

- repo: local
  hooks:
    - id: add inits
      name: add_inits
      language: system
      entry: bash -c \
        "for DIR in $(find \"./core\" -type d | grep -v templates); do
          touch $DIR/__init__.py;
        done"
default_stages: [commit]
